# comment this to get a black-on-white version
WOBDEF=-DWHITE_ON_BLACK

# -DSCALE=n sets how many times to scale up the window, 1=normal.
#  I wouldn't bother with it, it's far too slow. Also, it only works on
#  8-bit displays at the moment.
# -DMITSHM should always be enabled unless you have problems compiling
#  with it on
SCALEDEF=-DSCALE=2 -DMITSHM

# If you don't know where it is, try `/usr/X11', that's a common
# culprit. This is where it is on my Linux box:
XROOT=/usr/X11R6

# you shouldn't need to edit the rest
#-----------------------------------------------------------------

# this looks wrong, but *ops.c are actually #include'd by z80.c
ACE_OBJS=xmain.o z80.o

CFLAGS= -I$(XROOT)/include $(WOBDEF) $(SCALEDEF) -DXACE_VERSION='"(0.4.1)"'

all: xace

xace: $(ACE_OBJS)
	$(CC) -o xace $(ACE_OBJS) -L$(XROOT)/lib -lXext -lX11

z80.o: edops.c cbops.c z80ops.c z80.h 

clean:
	rm *.o *~

